### ISSUE TITLE
Stars location [Feature request]

### ISSUE THREAD

**Issue by iDre4M** [andmcadams/plugin-repo#2]
Would be nice to see extra feature that would simply confirm location of the star if someone using the plugin happens to come to the position or run by the star: f.e. on landing or when star has already landed.

World, location, (maybe tier), if active or depleted, mark on the map

**Comment by andmcadams** [comment]
I have thought about doing this in the future, but my main goal right now is adding filters to the list of stars and then doing a heavy refactoring of the code. Tracking the actual locations of the stars is a lot of work because I don't have anything set up to handle that (server side or client side).

**Comment by andmcadams** [comment]
I've decided not to do this for a variety of reasons, the main one being that there is no way for me to easily validate the actual locations. I imagine it would be flooded with fake data.
