### ISSUE TITLE
HTTP Authorization header does not comply with RFC 2617

### ISSUE THREAD

**Issue by Septem151** [andmcadams/plugin-repo#5]
The HTTP Authorization used for communicating with the API Server is not compliant with [RFC 2617][1]
The Authorization header should be as follows:
Key: Authorization
Value: Basic base64(username:password)

From the RFC docs:
```
 user-pass   = userid ":" password
      userid      = *<TEXT excluding ":">
      password    = *TEXT

   Userids might be case sensitive.

   If the user agent wishes to send the userid "Aladdin" and password
   "open sesame", it would use the following header field:

      Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==
```

Also, currently you can submit any data to the API Server with any Authorization header value as long as it's alpha characters, and there is no check in place to guarantee validity of the submission. I was able to POST fake star data using any value for the Auth header, and any values for the location, world, minTime, and maxTime. Likewise, there is no check on whether the data being submitted is of the proper type (ex: you can submit a string for world, when an integer is expected)

[1]: https://tools.ietf.org/html/rfc2617

**Comment by andmcadams** [comment]
Thanks for bringing this up. Does misusing the Authentication header actually have any negative affects here? My understanding is that the rfc suggests a standard for authentication rather than a rule. I am not attempting to do any "real" authentication here, the point of the keys is just to separate out the data so people can access their own. This was suggested to me by someone else who did something similar, though I'd be happy to change it if there are actual issues with it.

As for fake post data, in general there's little to nothing that I can do about this. There is no trivial way for me to determine whether or not data is fake if it looks real enough. I could implement something like a voting scheme, but that'd be just as trivial to overcome for someone who actually wanted to be malicious. Again, this is the point of the keys (and why I encourage people to use their own endpoints), I have no interest in policing the data to make sure it is legit. I will if I have to, but I would much rather people use their own endpoints/keys and only invite people they trust. The "global" default key is an unfortunate compromise because people were confused that the plugin didn't work out of the box. However, there are definitely some simple checks that I can/should add in, such as checking for sane times and valid worlds.

What post endpoint are you using? If you aren't using the default one I have no ability to change how data is handled as I don't control it. My server shouldn't allow you to submit strings for the world (for example), though it will return a 200 making it look like it did. That code is open sourced [here](https://github.com/andmcadams/shooting-stars-node).

**Comment by Septem151** [comment]
> What post endpoint are you using? If you aren't using the default one I have no ability to change how data is handled as I don't control it. My server shouldn't allow you to submit strings for the world (for example), though it will return a 200 making it look like it did. That code is open sourced [here](https://github.com/andmcadams/shooting-stars-node).

Ahh, I see. You're giving a 200 OK and "Shooting star data received" for every POST to `/stars` if it contains any array of data and any alpha key.

> Thanks for bringing this up. Does misusing the Authentication header actually have any negative effects here?

Nope! No sensitive information is being submitted, so you're fine. I figured I would point this out for the sake of complete, professional code, but it's by no means required.

Cheers
